name: care-a-dev

services:
  care_a_dev:
    image: ${IMAGE_NAME:-ghcr.io/satish1134/care-a-beauty-solution}:develop
    container_name: care_a_dev
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/care-a/dev/data:/app/data
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: 127.0.0.1
      PORT: "3002"

