[production]
prod-vps ansible_host=carebeautysolution.com ansible_user=deploy ansible_ssh_private_key_file=~/.ssh/care_deploy

[staging]
staging-vps ansible_host=staging.carebeautysolution.com ansible_user=deploy ansible_ssh_private_key_file=~/.ssh/care_deploy

[development]
dev-vps ansible_host=dev.carebeautysolution.com ansible_user=deploy ansible_ssh_private_key_file=~/.ssh/care_deploy

[all:vars]
ansible_python_interpreter=/usr/bin/python3
